# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 303)
        MainWindow.setMinimumSize(QtCore.QSize(654, 303))
        MainWindow.setMaximumSize(QtCore.QSize(654, 303))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 621, 271))
        self.frame.setStyleSheet("background-color:white; border-radius:30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.txt_job = QtWidgets.QLineEdit(self.frame)
        self.txt_job.setGeometry(QtCore.QRect(10, 150, 113, 20))
        self.txt_job.setStyleSheet("border-bottom:1px solid black;")
        self.txt_job.setObjectName("txt_job")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(160, 130, 47, 13))
        self.label_4.setObjectName("label_4")
        self.txt_email = QtWidgets.QLineEdit(self.frame)
        self.txt_email.setGeometry(QtCore.QRect(150, 150, 113, 20))
        self.txt_email.setStyleSheet("border-bottom:1px solid black;")
        self.txt_email.setObjectName("txt_email")
        self.rbd_darkmode = QtWidgets.QRadioButton(self.frame)
        self.rbd_darkmode.setGeometry(QtCore.QRect(510, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.rbd_darkmode.setFont(font)
        self.rbd_darkmode.setStyleSheet("QRadioButton{\n"
"background-color: rgb(167, 167, 167);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QRadioButton:indicator{\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator:unchecked{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator:checked{\n"
"background-color:black;\n"
"\n"
"}\n"
"\n"
"QRadioButton:hover:indicator:checked{\n"
"background-color:background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.rbd_darkmode.setIconSize(QtCore.QSize(21, 16))
        self.rbd_darkmode.setCheckable(True)
        self.rbd_darkmode.setChecked(False)
        self.rbd_darkmode.setAutoRepeat(True)
        self.rbd_darkmode.setAutoExclusive(False)
        self.rbd_darkmode.setObjectName("rbd_darkmode")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(310, 130, 47, 13))
        self.label_5.setObjectName("label_5")
        self.txt_cpf = QtWidgets.QLineEdit(self.frame)
        self.txt_cpf.setGeometry(QtCore.QRect(290, 150, 113, 20))
        self.txt_cpf.setStyleSheet("border-bottom:1px solid black;")
        self.txt_cpf.setObjectName("txt_cpf")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(30, 210, 69, 22))
        self.comboBox.setStyleSheet("border: 1px solid black;")
        self.comboBox.setObjectName("comboBox")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(150, 190, 81, 16))
        self.label_7.setObjectName("label_7")
        self.txt_phonenumber = QtWidgets.QLineEdit(self.frame)
        self.txt_phonenumber.setGeometry(QtCore.QRect(150, 210, 113, 20))
        self.txt_phonenumber.setStyleSheet("border-bottom:1px solid black;")
        self.txt_phonenumber.setObjectName("txt_phonenumber")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(210, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.btn_register = QtWidgets.QPushButton(self.frame)
        self.btn_register.setGeometry(QtCore.QRect(530, 230, 75, 23))
        self.btn_register.setStyleSheet("QPushButton{\n"
"border:1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font-weight:bold;\n"
"}")
        self.btn_register.setObjectName("btn_register")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(290, 210, 21, 16))
        self.label_9.setObjectName("label_9")
        self.lbl_id = QtWidgets.QLabel(self.frame)
        self.lbl_id.setGeometry(QtCore.QRect(320, 212, 47, 13))
        self.lbl_id.setText("")
        self.lbl_id.setObjectName("lbl_id")
        self.btn_back = QtWidgets.QPushButton(self.frame)
        self.btn_back.setGeometry(QtCore.QRect(440, 230, 75, 23))
        self.btn_back.setStyleSheet("QPushButton{\n"
"border:1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font-weight:bold;\n"
"\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(160, 60, 61, 16))
        self.label_2.setObjectName("label_2")
        self.rbd_men = QtWidgets.QRadioButton(self.frame)
        self.rbd_men.setGeometry(QtCore.QRect(150, 90, 82, 17))
        self.rbd_men.setAutoRepeat(True)
        self.rbd_men.setObjectName("rbd_men")
        self.rbd_woman = QtWidgets.QRadioButton(self.frame)
        self.rbd_woman.setGeometry(QtCore.QRect(200, 90, 82, 17))
        self.rbd_woman.setAutoRepeat(True)
        self.rbd_woman.setObjectName("rbd_woman")
        self.txt_name = QtWidgets.QLineEdit(self.frame)
        self.txt_name.setGeometry(QtCore.QRect(10, 84, 113, 20))
        self.txt_name.setStyleSheet("border:none;\n"
"border-bottom:1px solid black;")
        self.txt_name.setObjectName("txt_name")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registration"))
        self.label_3.setText(_translate("MainWindow", "Your Job"))
        self.label_4.setText(_translate("MainWindow", "Email"))
        self.rbd_darkmode.setText(_translate("MainWindow", "Dark Mode off"))
        self.label_5.setText(_translate("MainWindow", "CPF"))
        self.txt_cpf.setInputMask(_translate("MainWindow", "000.000.000-00"))
        self.label_6.setText(_translate("MainWindow", "Type phone"))
        self.label_7.setText(_translate("MainWindow", "Phone Number"))
        self.label_8.setText(_translate("MainWindow", "Registration"))
        self.btn_register.setText(_translate("MainWindow", "Register"))
        self.label_9.setText(_translate("MainWindow", "ID:"))
        self.btn_back.setText(_translate("MainWindow", "Back"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Your sex?"))
        self.rbd_men.setText(_translate("MainWindow", "Men"))
        self.rbd_woman.setText(_translate("MainWindow", "Woman"))
