# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 303)
        MainWindow.setMinimumSize(QtCore.QSize(654, 303))
        MainWindow.setMaximumSize(QtCore.QSize(654, 303))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 90, 47, 13))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 110, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 90, 61, 16))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(180, 110, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 110, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 621, 271))
        self.frame.setStyleSheet("background-color:white; border-radius:30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 150, 113, 20))
        self.lineEdit_2.setStyleSheet("border:1px solid black;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(160, 130, 47, 13))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 150, 113, 20))
        self.lineEdit_3.setStyleSheet("border:1px solid black;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.rbd_darkmode = QtWidgets.QRadioButton(self.frame)
        self.rbd_darkmode.setGeometry(QtCore.QRect(510, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.rbd_darkmode.setFont(font)
        self.rbd_darkmode.setStyleSheet("QRadioButton{\n"
"background-color: rgb(167, 167, 167);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QRadioButton:indicator{\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator:unchecked{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator:checked{\n"
"background-color:black;\n"
"\n"
"}\n"
"\n"
"QRadioButton:hover:indicator:checked{\n"
"background-color:background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.rbd_darkmode.setIconSize(QtCore.QSize(21, 16))
        self.rbd_darkmode.setCheckable(True)
        self.rbd_darkmode.setChecked(False)
        self.rbd_darkmode.setAutoRepeat(True)
        self.rbd_darkmode.setObjectName("rbd_darkmode")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(310, 130, 47, 13))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 150, 113, 20))
        self.lineEdit_4.setStyleSheet("border:1px solid black;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(30, 210, 69, 22))
        self.comboBox.setStyleSheet("border: 1px solid black;")
        self.comboBox.setObjectName("comboBox")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(150, 190, 81, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 210, 113, 20))
        self.lineEdit_5.setStyleSheet("border:1px solid black;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(240, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(480, 220, 75, 23))
        self.pushButton.setStyleSheet("border:1px solid black;")
        self.pushButton.setObjectName("pushButton")
        self.frame.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registration"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Your sex?"))
        self.radioButton.setText(_translate("MainWindow", "Men"))
        self.radioButton_2.setText(_translate("MainWindow", "Woman"))
        self.label_3.setText(_translate("MainWindow", "Your Job"))
        self.label_4.setText(_translate("MainWindow", "Email"))
        self.rbd_darkmode.setText(_translate("MainWindow", "Dark Mode off"))
        self.label_5.setText(_translate("MainWindow", "CPF"))
        self.lineEdit_4.setInputMask(_translate("MainWindow", "000.000.000-00"))
        self.label_6.setText(_translate("MainWindow", "Type phone"))
        self.label_7.setText(_translate("MainWindow", "Phone Number"))
        self.label_8.setText(_translate("MainWindow", "Registration"))
        self.pushButton.setText(_translate("MainWindow", "Register"))
