# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_crud.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 648)
        MainWindow.setMinimumSize(QtCore.QSize(814, 648))
        MainWindow.setMaximumSize(QtCore.QSize(814, 648))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/agenda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(243, 243, 243);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:transparent;\n"
"color:black;\n"
"border:none;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border-bottom: 2px solid black;\n"
"\n"
"}\n"
"\n"
"QPushButton:clicked{\n"
"\n"
"font-weight:normal;\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"color:black;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qtable_contacts = QtWidgets.QTableWidget(self.centralwidget)
        self.qtable_contacts.setGeometry(QtCore.QRect(20, 260, 781, 371))
        self.qtable_contacts.setStyleSheet("QTableWidget{\n"
"color:white;\n"
"background-color:white;\n"
"}")
        self.qtable_contacts.setObjectName("qtable_contacts")
        self.qtable_contacts.setColumnCount(8)
        self.qtable_contacts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.qtable_contacts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.qtable_contacts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.qtable_contacts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.qtable_contacts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.qtable_contacts.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.qtable_contacts.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.qtable_contacts.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.qtable_contacts.setHorizontalHeaderItem(7, item)
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(126, 20, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(30)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setEnabled(True)
        self.btn_insert.setGeometry(QtCore.QRect(241, 225, 91, 20))
        self.btn_insert.setMinimumSize(QtCore.QSize(91, 20))
        self.btn_insert.setMaximumSize(QtCore.QSize(91, 20))
        self.btn_insert.setObjectName("btn_insert")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(455, 225, 91, 20))
        self.btn_delete.setMinimumSize(QtCore.QSize(91, 20))
        self.btn_delete.setMaximumSize(QtCore.QSize(91, 20))
        self.btn_delete.setObjectName("btn_delete")
        self.txt_cpf_search = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cpf_search.setGeometry(QtCore.QRect(270, 109, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.txt_cpf_search.setFont(font)
        self.txt_cpf_search.setStyleSheet("QLineEdit{\n"
"border-bottom: 30px solid black;\n"
"background-color:transparent;\n"
"color:black;\n"
"}")
        self.txt_cpf_search.setFrame(True)
        self.txt_cpf_search.setObjectName("txt_cpf_search")
        self.btn_search_cpf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search_cpf.setGeometry(QtCore.QRect(350, 150, 75, 23))
        self.btn_search_cpf.setObjectName("btn_search_cpf")
        self.btn_update = QtWidgets.QPushButton(self.centralwidget)
        self.btn_update.setGeometry(QtCore.QRect(349, 225, 91, 20))
        self.btn_update.setMinimumSize(QtCore.QSize(91, 20))
        self.btn_update.setMaximumSize(QtCore.QSize(91, 20))
        self.btn_update.setObjectName("btn_update")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 80, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.rbd_darkmode = QtWidgets.QRadioButton(self.centralwidget)
        self.rbd_darkmode.setGeometry(QtCore.QRect(680, 27, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.rbd_darkmode.setFont(font)
        self.rbd_darkmode.setStyleSheet("QRadioButton{\n"
"background-color: rgb(167, 167, 167);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QRadioButton:indicator{\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator:unchecked{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator:checked{\n"
"background-color:black;\n"
"\n"
"}\n"
"\n"
"QRadioButton:hover:indicator:checked{\n"
"background-color:background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.rbd_darkmode.setIconSize(QtCore.QSize(21, 16))
        self.rbd_darkmode.setCheckable(True)
        self.rbd_darkmode.setChecked(False)
        self.rbd_darkmode.setAutoRepeat(True)
        self.rbd_darkmode.setObjectName("rbd_darkmode")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CRUD BY  YURI ALVES LIMA"))
        item = self.qtable_contacts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.qtable_contacts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.qtable_contacts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sex"))
        item = self.qtable_contacts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Job"))
        item = self.qtable_contacts.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.qtable_contacts.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.qtable_contacts.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Type Phone"))
        item = self.qtable_contacts.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Phone Number"))
        self.lbl_title.setText(_translate("MainWindow", "Contacts list"))
        self.btn_insert.setText(_translate("MainWindow", "Insert"))
        self.btn_delete.setText(_translate("MainWindow", "Delete"))
        self.txt_cpf_search.setInputMask(_translate("MainWindow", "000.000.000-00"))
        self.txt_cpf_search.setPlaceholderText(_translate("MainWindow", "Search contact by CPF"))
        self.btn_search_cpf.setText(_translate("MainWindow", "Search"))
        self.btn_update.setText(_translate("MainWindow", "Update"))
        self.label.setText(_translate("MainWindow", "Write your CPF to search:"))
        self.rbd_darkmode.setText(_translate("MainWindow", "Dark Mode off"))
